# Generated by Django 6.0.8 on 2026-09-13 03:45

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "supplier_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "base_unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "net_purchase_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="IDR", max_length=3),
                ),
                (
                    "available_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("calculation_version", models.CharField(max_length=32)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_supplier_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="catalog.product",
                    ),
                ),
                (
                    "supersedes_offer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseding_offer",
                        to="sourcing.supplieroffer",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="catalog.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "sourcing_supplier_offer",
                "ordering": (
                    "product__name",
                    "net_purchase_price",
                    "supplier__code",
                ),
                "indexes": [
                    models.Index(
                        fields=["product", "is_active", "valid_until"],
                        name="sourcing_su_product_9d45a6_idx",
                    ),
                    models.Index(
                        fields=["supplier", "product", "created_at"],
                        name="sourcing_su_supplie_31b84d_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("base_unit_price__gt", 0)),
                        name="sourcing_offer_base_price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_percent__gte", 0),
                            ("discount_percent__lte", 100),
                        ),
                        name="sourcing_offer_discount_bounded",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("net_purchase_price__gte", 0)),
                        name="sourcing_offer_net_price_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("available_quantity__isnull", True),
                            ("available_quantity__gt", 0),
                            _connector="OR",
                        ),
                        name="sourcing_offer_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "IDR")),
                        name="sourcing_offer_currency_idr",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_from__isnull", True),
                            ("valid_until__isnull", True),
                            ("valid_until__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="sourcing_offer_valid_date_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="sourcing_offer_version_positive",
                    ),
                ],
            },
        ),
    ]
