# Generated by Django 6.0.8 on 2026-09-13 07:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
        ('tender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('OPTIMIZER', 'Optimizer'), ('CUSTOMIZED', 'Customized')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALID', 'Valid')], default='DRAFT', max_length=20)),
                ('optimization_run_id', models.UUIDField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('total_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('calculation_version', models.CharField(max_length=32)),
                ('snapshot_schema_version', models.PositiveIntegerField(blank=True, null=True)),
                ('result_snapshot', models.JSONField(blank=True, null=True)),
                ('result_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_procurement_results', to=settings.AUTH_USER_MODEL)),
                ('source_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customized_results', to='sourcing.procurementresult')),
                ('tender_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_results', to='tender.tenderrequestrevision')),
            ],
            options={
                'db_table': 'sourcing_procurement_result',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProcurementResultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('requested_quantity_snapshot', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_snapshot', models.CharField(max_length=32)),
                ('item_purchase_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('product_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sourcing.procurementresult')),
                ('tender_request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_result_items', to='tender.tenderrequestitem')),
            ],
            options={
                'db_table': 'sourcing_procurement_result_item',
                'ordering': ('line_number',),
            },
        ),
        migrations.CreateModel(
            name='ProcurementResultSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selection_number', models.PositiveIntegerField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('procurement_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='sourcing.procurementresult')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_result_selections', to=settings.AUTH_USER_MODEL)),
                ('tender_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_selections', to='tender.tenderrequest')),
                ('tender_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_selections', to='tender.tenderrequestrevision')),
            ],
            options={
                'db_table': 'sourcing_procurement_result_selection',
                'ordering': ('-selection_number',),
            },
        ),
        migrations.CreateModel(
            name='SupplierAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('allocated_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('base_unit_price_snapshot', models.DecimalField(decimal_places=4, max_digits=20)),
                ('discount_percent_snapshot', models.DecimalField(decimal_places=4, max_digits=7)),
                ('net_purchase_price_snapshot', models.DecimalField(decimal_places=4, max_digits=20)),
                ('allocation_purchase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('supplier_snapshot', models.JSONField()),
                ('offer_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement_result_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sourcing.procurementresultitem')),
                ('supplier_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sourcing.supplieroffer')),
            ],
            options={
                'db_table': 'sourcing_supplier_allocation',
                'ordering': ('procurement_result_item__line_number', 'line_number'),
            },
        ),
        migrations.AddIndex(
            model_name='procurementresult',
            index=models.Index(fields=['tender_revision', 'status', 'total_purchase'], name='src_result_tender_status_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementresult',
            index=models.Index(fields=['optimization_run_id', 'rank'], name='src_result_run_rank_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurementresult',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='sourcing_result_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='procurementresult',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'IDR')), name='sourcing_result_currency_idr'),
        ),
        migrations.AddConstraint(
            model_name='procurementresult',
            constraint=models.CheckConstraint(condition=models.Q(('rank__isnull', True), ('rank__gt', 0), _connector='OR'), name='sourcing_result_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='procurementresult',
            constraint=models.CheckConstraint(condition=models.Q(('total_purchase__isnull', True), ('total_purchase__gt', 0), _connector='OR'), name='sourcing_result_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='procurementresult',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_schema_version__isnull', True), ('snapshot_schema_version__gt', 0), _connector='OR'), name='sourcing_result_schema_positive'),
        ),
        migrations.AddConstraint(
            model_name='procurementresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('optimization_run_id__isnull', True), ('rank__isnull', True), ('source_result__isnull', True), ('source_type', 'MANUAL')), models.Q(('optimization_run_id__isnull', True), ('rank__isnull', True), ('source_result__isnull', False), ('source_type', 'CUSTOMIZED')), models.Q(('optimization_run_id__isnull', False), ('rank__isnull', False), ('source_result__isnull', True), ('source_type', 'OPTIMIZER')), _connector='OR'), name='sourcing_result_source_lineage_valid'),
        ),
        migrations.AddConstraint(
            model_name='procurementresult',
            constraint=models.CheckConstraint(condition=models.Q(('source_result__isnull', True), models.Q(('source_result', models.F('id')), _negated=True), _connector='OR'), name='sourcing_result_source_not_self'),
        ),
        migrations.AddConstraint(
            model_name='procurementresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('result_hash__isnull', True), ('result_snapshot__isnull', True), ('snapshot_schema_version__isnull', True), ('status', 'DRAFT'), ('total_purchase__isnull', True), ('validated_at__isnull', True)), models.Q(('result_hash__isnull', False), ('result_snapshot__isnull', False), ('snapshot_schema_version__isnull', False), ('status', 'VALID'), ('total_purchase__isnull', False), ('validated_at__isnull', False)), _connector='OR'), name='sourcing_result_state_payload_valid'),
        ),
        migrations.AddConstraint(
            model_name='procurementresult',
            constraint=models.UniqueConstraint(condition=models.Q(('optimization_run_id__isnull', False)), fields=('optimization_run_id', 'rank'), name='sourcing_result_run_rank_unique'),
        ),
        migrations.AddConstraint(
            model_name='procurementresultitem',
            constraint=models.UniqueConstraint(fields=('procurement_result', 'tender_request_item'), name='sourcing_result_item_tender_unique'),
        ),
        migrations.AddConstraint(
            model_name='procurementresultitem',
            constraint=models.UniqueConstraint(fields=('procurement_result', 'line_number'), name='sourcing_result_item_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='procurementresultitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='sourcing_result_item_line_positive'),
        ),
        migrations.AddConstraint(
            model_name='procurementresultitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity_snapshot__gt', 0)), name='sourcing_result_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='procurementresultitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_purchase_total__isnull', True), ('item_purchase_total__gt', 0), _connector='OR'), name='sourcing_result_item_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='procurementresultitem',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'IDR')), name='sourcing_result_item_currency_idr'),
        ),
        migrations.AddIndex(
            model_name='procurementresultselection',
            index=models.Index(fields=['tender_request', '-selection_number'], name='sourcing_selection_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurementresultselection',
            constraint=models.UniqueConstraint(fields=('tender_request', 'selection_number'), name='sourcing_selection_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='procurementresultselection',
            constraint=models.CheckConstraint(condition=models.Q(('selection_number__gt', 0)), name='sourcing_selection_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierallocation',
            constraint=models.UniqueConstraint(fields=('procurement_result_item', 'line_number'), name='sourcing_allocation_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierallocation',
            constraint=models.UniqueConstraint(fields=('procurement_result_item', 'supplier_offer'), name='sourcing_allocation_offer_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierallocation',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='sourcing_allocation_line_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_quantity__gt', 0)), name='sourcing_allocation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierallocation',
            constraint=models.CheckConstraint(condition=models.Q(('base_unit_price_snapshot__gt', 0)), name='sourcing_allocation_base_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierallocation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent_snapshot__gte', 0), ('discount_percent_snapshot__lte', 100)), name='sourcing_allocation_discount_bounded'),
        ),
        migrations.AddConstraint(
            model_name='supplierallocation',
            constraint=models.CheckConstraint(condition=models.Q(('net_purchase_price_snapshot__gt', 0)), name='sourcing_allocation_net_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocation_purchase__gt', 0)), name='sourcing_allocation_purchase_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierallocation',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'IDR')), name='sourcing_allocation_currency_idr'),
        ),
    ]
