# Generated by Django 6.0.8 on 2026-09-11 13:03

import django.db.models.functions.text
from django.db import migrations, models

import apps.accounts.models


def normalize_existing_users(apps, schema_editor):
    """Siapkan data lama sebelum constraint account diterapkan."""

    user_model = apps.get_model("accounts", "User")
    valid_roles = ("ADMIN", "PROCUREMENT_STAFF", "MANAGER")

    invalid_regular_users = user_model.objects.filter(
        is_superuser=False,
    ).exclude(role__in=valid_roles)
    if invalid_regular_users.exists():
        raise RuntimeError(
            "Perbaiki role user non-superuser sebelum migration accounts."
        )

    incomplete_regular_users = user_model.objects.filter(
        is_superuser=False,
    ).filter(models.Q(email="") | models.Q(full_name=""))
    if incomplete_regular_users.exists():
        raise RuntimeError(
            "Perbaiki email/full_name user sebelum migration accounts."
        )

    user_model.objects.filter(is_superuser=True).update(
        role="ADMIN",
        is_staff=True,
    )
    user_model.objects.filter(
        is_superuser=True,
        full_name="",
    ).update(full_name="System Administrator")
    user_model.objects.filter(role="ADMIN").update(is_staff=True)
    user_model.objects.exclude(role="ADMIN").update(is_staff=False)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.AccountUserManager()),
            ],
        ),
        migrations.RunPython(
            normalize_existing_users,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role__in", ["ADMIN", "PROCUREMENT_STAFF", "MANAGER"])
                ),
                name="accounts_user_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_staff", False), ("role", "ADMIN"), _connector="OR"
                ),
                name="accounts_user_staff_requires_admin_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="accounts_user_username_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="accounts_user_email_ci_unique",
            ),
        ),
    ]
