# Generated by Django 6.0.8 on 2026-09-13 14:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('signatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'documents_number_sequence',
            },
        ),
        migrations.CreateModel(
            name='DocumentGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('RUNNING', 'Diproses'), ('COMPLETED', 'Selesai'), ('FAILED', 'Gagal')], default='PENDING', max_length=20)),
                ('document_version', models.PositiveIntegerField()),
                ('template_version', models.CharField(default='1', max_length=32)),
                ('snapshot_schema_version', models.PositiveIntegerField()),
                ('input_snapshot', models.JSONField()),
                ('input_hash', models.CharField(max_length=64)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('safe_error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('safe_error_message', models.TextField(blank=True, null=True)),
                ('diagnostic_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='bids.bidproposalrevision')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_document_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_generation_job',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FinalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_version', models.PositiveIntegerField()),
                ('document_number', models.CharField(max_length=100)),
                ('template_version', models.CharField(max_length=32)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('object_version_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('snapshot_schema_version', models.PositiveIntegerField()),
                ('content_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_documents', to='bids.bidproposalrevision')),
                ('finalized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalized_documents', to=settings.AUTH_USER_MODEL)),
                ('generation_job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_document', to='documents.documentgenerationjob')),
            ],
            options={
                'db_table': 'documents_final_document',
                'ordering': ('-document_version', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='documentgenerationjob',
            index=models.Index(fields=['status', 'created_at'], name='document_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentgenerationjob',
            index=models.Index(fields=['bid_revision', '-document_version'], name='document_job_revision_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentgenerationjob',
            constraint=models.UniqueConstraint(fields=('bid_revision', 'document_version'), name='document_job_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(('document_version__gt', 0)), name='document_job_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='documentgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_schema_version__gt', 0)), name='document_job_schema_positive'),
        ),
        migrations.AddConstraint(
            model_name='documentgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='document_job_row_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='documentgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status__in', ('PENDING', 'RUNNING'))), models.Q(('completed_at__isnull', False), ('safe_error_code__isnull', True), ('status', 'COMPLETED')), models.Q(('completed_at__isnull', False), ('safe_error_code__isnull', False), ('status', 'FAILED')), _connector='OR'), name='document_job_terminal_payload_valid'),
        ),
        migrations.AddIndex(
            model_name='finaldocument',
            index=models.Index(fields=['bid_revision', '-document_version'], name='final_document_revision_idx'),
        ),
        migrations.AddConstraint(
            model_name='finaldocument',
            constraint=models.UniqueConstraint(fields=('bid_revision', 'document_version'), name='final_document_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='finaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('document_version__gt', 0)), name='final_document_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='finaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='final_document_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='finaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_schema_version__gt', 0)), name='final_document_schema_positive'),
        ),
        migrations.AddConstraint(
            model_name='finaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('mime_type', 'application/pdf')), name='final_document_pdf_mime'),
        ),
    ]
