# Generated by Django 6.0.8 on 2026-09-13 14:36

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0002_initial'),
        ('bids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_name', models.CharField(max_length=255)),
                ('signed_snapshot_hash', models.CharField(max_length=64)),
                ('image_object_key', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('image_version_id', models.CharField(blank=True, max_length=255, null=True)),
                ('image_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('image_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature', to='approval.approvaldecision')),
                ('bid_revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature', to='bids.bidproposalrevision')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signatures_signature',
                'ordering': ('-signed_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('image_mime_type__isnull', True), ('image_object_key__isnull', True), ('image_sha256__isnull', True), ('image_size_bytes__isnull', True), ('image_version_id__isnull', True)), models.Q(('image_mime_type__in', ('image/png', 'image/jpeg')), ('image_object_key__isnull', False), ('image_sha256__isnull', False), ('image_size_bytes__gt', 0), ('image_size_bytes__lte', 1048576)), _connector='OR'), name='signature_image_metadata_valid')],
            },
        ),
    ]
