# Generated by Django 6.0.8 on 2026-09-13 13:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0003_procurementresult_optimization_run_fk'),
        ('tender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_number', models.CharField(max_length=50, unique=True)),
                ('current_revision_number', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bid_proposals', to=settings.AUTH_USER_MODEL)),
                ('tender_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_proposals', to='tender.tenderrequest')),
            ],
            options={
                'db_table': 'bids_bid_proposal',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BidProposalRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_APPROVAL', 'Menunggu approval'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('SIGNED', 'Ditandatangani'), ('FINALIZED', 'Final')], default='DRAFT', max_length=24)),
                ('target_margin_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('total_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_bid_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('actual_margin_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('max_margin_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('is_hps_feasible', models.BooleanField(blank=True, null=True)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('calculation_version', models.CharField(max_length=32)),
                ('snapshot_schema_version', models.PositiveIntegerField()),
                ('selected_result_snapshot', models.JSONField()),
                ('submission_snapshot', models.JSONField(blank=True, null=True)),
                ('submission_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='bids.bidproposal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bid_revisions', to=settings.AUTH_USER_MODEL)),
                ('selected_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_revisions', to='sourcing.procurementresult')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_bid_revisions', to=settings.AUTH_USER_MODEL)),
                ('tender_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_revisions', to='tender.tenderrequestrevision')),
            ],
            options={
                'db_table': 'bids_bid_proposal_revision',
                'ordering': ('-revision_number',),
            },
        ),
        migrations.CreateModel(
            name='BidProposalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('product_snapshot', models.JSONField()),
                ('requested_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit', models.CharField(max_length=32)),
                ('item_purchase_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_purchase_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('bid_unit_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('item_bid_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender_request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_items', to='tender.tenderrequestitem')),
                ('bid_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bids.bidproposalrevision')),
            ],
            options={
                'db_table': 'bids_bid_proposal_item',
                'ordering': ('line_number',),
            },
        ),
        migrations.AddIndex(
            model_name='bidproposal',
            index=models.Index(fields=['tender_request', '-created_at'], name='bid_tender_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='bidproposal',
            constraint=models.CheckConstraint(condition=models.Q(('current_revision_number__gt', 0)), name='bid_current_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposal',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='bid_root_version_positive'),
        ),
        migrations.AddIndex(
            model_name='bidproposalrevision',
            index=models.Index(fields=['status', '-updated_at'], name='bid_revision_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.UniqueConstraint(fields=('bid_proposal', 'revision_number'), name='bid_revision_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gt', 0)), name='bid_revision_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='bid_revision_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_schema_version__gt', 0)), name='bid_revision_schema_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'IDR')), name='bid_revision_currency_idr'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.CheckConstraint(condition=models.Q(('target_margin_percent__isnull', True), models.Q(('target_margin_percent__gte', 0), ('target_margin_percent__lt', 100)), _connector='OR'), name='bid_revision_margin_bounded'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.CheckConstraint(condition=models.Q(('total_purchase__isnull', True), ('total_purchase__gt', 0), _connector='OR'), name='bid_revision_purchase_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.CheckConstraint(condition=models.Q(('total_bid_value__isnull', True), ('total_bid_value__gt', 0), _connector='OR'), name='bid_revision_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.CheckConstraint(condition=models.Q(('gross_profit__isnull', True), ('gross_profit__gte', 0), _connector='OR'), name='bid_revision_profit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_margin_percent__isnull', True), ('gross_profit__isnull', True), ('is_hps_feasible__isnull', True), ('max_margin_percent__isnull', True), ('target_margin_percent__isnull', True), ('total_bid_value__isnull', True)), models.Q(('actual_margin_percent__isnull', False), ('gross_profit__isnull', False), ('target_margin_percent__isnull', False), ('total_bid_value__isnull', False), ('total_purchase__isnull', False)), _connector='OR'), name='bid_revision_pricing_payload_valid'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), ('submission_hash__isnull', True), ('submission_snapshot__isnull', True), ('submitted_at__isnull', True), ('submitted_by__isnull', True)), models.Q(('actual_margin_percent__isnull', False), ('gross_profit__isnull', False), ('status__in', ('WAITING_APPROVAL', 'APPROVED', 'REJECTED', 'SIGNED', 'FINALIZED')), ('submission_hash__isnull', False), ('submission_snapshot__isnull', False), ('submitted_at__isnull', False), ('submitted_by__isnull', False), ('target_margin_percent__isnull', False), ('total_bid_value__isnull', False), ('total_purchase__isnull', False)), _connector='OR'), name='bid_revision_submission_payload_valid'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalitem',
            constraint=models.UniqueConstraint(fields=('bid_revision', 'tender_request_item'), name='bid_item_tender_unique'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalitem',
            constraint=models.UniqueConstraint(fields=('bid_revision', 'line_number'), name='bid_item_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='bid_item_line_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='bid_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_purchase_total__gt', 0)), name='bid_item_purchase_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_purchase_cost__gt', 0)), name='bid_item_unit_purchase_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalitem',
            constraint=models.CheckConstraint(condition=models.Q(('bid_unit_price__gt', 0)), name='bid_item_unit_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_bid_total__gt', 0)), name='bid_item_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='bidproposalitem',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'IDR')), name='bid_item_currency_idr'),
        ),
    ]
