# Generated by Django 6.0.8 on 2026-09-11 13:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_name", models.CharField(max_length=255)),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.UUIDField()),
                (
                    "entity_revision",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("action", models.CharField(max_length=64)),
                (
                    "from_status",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "to_status",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("correlation_id", models.CharField(max_length=100)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_audit_event",
                "ordering": ("-occurred_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("entity_revision__isnull", True),
                            ("entity_revision__gt", 0),
                            _connector="OR",
                        ),
                        name="audit_event_revision_positive",
                    )
                ],
            },
        ),
    ]
