# Generated by Django 6.0.8 on 2026-09-13 03:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenderRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "internal_code",
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    "current_revision_number",
                    models.PositiveIntegerField(default=1),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tenders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tender_tender_request",
                "ordering": ("-created_at", "internal_code"),
            },
        ),
        migrations.CreateModel(
            name="TenderRequestRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                (
                    "tender_reference_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("institution_name", models.CharField(max_length=255)),
                ("institution_address", models.TextField(blank=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "currency",
                    models.CharField(default="IDR", max_length=3),
                ),
                (
                    "total_hps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("revision_reason", models.TextField(blank=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tender_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tender_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="tender.tenderrequest",
                    ),
                ),
            ],
            options={
                "db_table": "tender_tender_request_revision",
                "ordering": ("-revision_number",),
            },
        ),
        migrations.CreateModel(
            name="TenderRequestItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                ("product_snapshot", models.JSONField()),
                (
                    "requested_quantity",
                    models.DecimalField(decimal_places=3, max_digits=18),
                ),
                ("unit", models.CharField(max_length=32)),
                ("specification", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tender_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "tender_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tender.tenderrequestrevision",
                    ),
                ),
            ],
            options={
                "db_table": "tender_tender_request_item",
                "ordering": ("line_number",),
            },
        ),
        migrations.AddIndex(
            model_name="tenderrequest",
            index=models.Index(
                fields=["created_at"],
                name="tender_tend_created_a078ba_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_revision_number__gt", 0)),
                name="tender_current_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)),
                name="tender_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderrequestrevision",
            constraint=models.UniqueConstraint(
                fields=("tender_request", "revision_number"),
                name="tender_revision_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderrequestrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision_number__gt", 0)),
                name="tender_revision_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderrequestrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_hps__isnull", True),
                    ("total_hps__gt", 0),
                    _connector="OR",
                ),
                name="tender_revision_hps_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderrequestrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "IDR")),
                name="tender_revision_currency_idr",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderrequestitem",
            constraint=models.UniqueConstraint(
                fields=("tender_revision", "line_number"),
                name="tender_item_line_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_number__gt", 0)),
                name="tender_item_line_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_quantity__gt", 0)),
                name="tender_item_quantity_positive",
            ),
        ),
    ]
