# Generated by Django 6.0.8 on 2026-09-13 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0001_initial'),
        ('bids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldecision',
            name='bid_revision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decision', to='bids.bidproposalrevision'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='decided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['decided_by', '-decided_at'], name='approval_manager_decided_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'APPROVED'), ('reason__isnull', True)), models.Q(('decision', 'REJECTED'), ('reason__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='approval_decision_reason_valid'),
        ),
    ]
