# Generated by Django 6.0.8 on 2026-09-13 13:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('OPTIMIZATION_COMPLETED', 'Optimization selesai'), ('OPTIMIZATION_FAILED', 'Optimization gagal'), ('BID_REJECTED', 'Bid ditolak')], max_length=40)),
                ('source_event_id', models.UUIDField()),
                ('source_entity_type', models.CharField(max_length=64)),
                ('source_entity_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notif_recipient_read_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'source_event_id', 'type'), name='notification_event_recipient_unique')],
            },
        ),
    ]
