# Generated by Django 6.0.8 on 2026-09-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OPTIMIZATION_COMPLETED', 'Optimization selesai'), ('OPTIMIZATION_FAILED', 'Optimization gagal'), ('BID_REJECTED', 'Bid ditolak'), ('DOCUMENT_COMPLETED', 'Dokumen selesai'), ('DOCUMENT_FAILED', 'Dokumen gagal')], max_length=40),
        ),
    ]
