# Generated by Django 6.0.8 on 2026-09-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BID_WAITING_APPROVAL', 'Bid menunggu approval'), ('OPTIMIZATION_COMPLETED', 'Optimization selesai'), ('OPTIMIZATION_FAILED', 'Optimization gagal'), ('BID_APPROVED', 'Bid disetujui'), ('BID_REJECTED', 'Bid ditolak'), ('BID_SIGNED', 'Bid ditandatangani'), ('DOCUMENT_COMPLETED', 'Dokumen selesai'), ('DOCUMENT_FAILED', 'Dokumen gagal')], max_length=40),
        ),
    ]
